### PR TITLE
Update to cachi2 0.9.1

### PR DESCRIPTION
**Pull request by eskultety**
https://github.com/containerbuildsystem/cachi2/releases/tag/0.9.1

# Before you complete this pull request ...

Look for any open pull requests in the repository with the title "e2e-tests update" and 
see if there are recent e2e-tests updates that will be applicable to your change.

### CODE REVIEW

**Review by MartinBasti — APPROVED** [review]

**Comment by tkdchen** [comment]
Included in #1186. But, there is a bug in the image of version 0.9.0 https://github.com/konflux-ci/build-definitions/pull/1186#issuecomment-2247199248

**Review by MartinBasti — CHANGES_REQUESTED** [review]
blocking merging until missing script is installed

**Review by chmeliik — APPROVED** [review]

**Review by MartinBasti — APPROVED** [review]

**Pull request merged**
