### PR TITLE
feat(KONFLUX-5480): Convert FBC pipeline to use trusted artifacts

### PR DESCRIPTION
**Pull request by arewm**
This also changes the FBC pipeline to be multi-arch enabled by default.

# Before you complete this pull request ...

Look for any open pull requests in the repository with the title "e2e-tests update" and 
see if there are recent e2e-tests updates that will be applicable to your change.

### CODE REVIEW

**Review by chmeliik — COMMENTED** [review]
Why does FBC need to be multi-arch? Isn't it basically just a container of text files?

**Comment by arewm** [comment]
The image contains an OPM binary which is used to serve the graph metadata for OLM. The indexes will be made multi-arch upon release as IIB requests do the conversion. If a user wants to test the FBC fragments before release, however, they will need to build the component as multi-arch to enable testing on all platforms.

This change still builds x86 images by default but lets users optionally add platforms. (this change also will have a side effect of adding the in-cluster remote task to e2e tests).

**Review by chmeliik — APPROVED** [review]
Not sure if the FBC pipeline needs prefetch-dependencies, otherwise LGTM

**Pull request merged**
