### PR TITLE
Add buildah-remote-oci-ta

### PR DESCRIPTION
**Pull request by stuartwdouglas**

### CODE REVIEW

**Comment by stuartwdouglas** [comment]
Note that this is just an initial implementation, when all involved images are multi-platform we can likely do a much more efficient implementation that does not rely on rsync.

**Comment by brianwcook** [comment]
@ralphbean  should the build for this be pushed to https://quay.io/organization/redhat-appstudio-tekton-catalog or to the new quay.io Konflux org?

**Comment by stuartwdouglas** [comment]
We should probably just wait until https://github.com/konflux-ci/build-definitions/pull/1041 is in, and then only push it to konflux-ci

**Comment by brianwcook** [comment]
1041 is in

**Review by arewm — APPROVED** [review]

**Pull request merged**
