### PR TITLE
build-and-push: escape annotation values

### PR DESCRIPTION
**Pull request by chmeliik**
Due to https://github.com/tektoncd/cli/issues/2402, annotation values that contain commas or double-quotes currently break 'tkn bundle push'.

Escape such annotation values in a way that's compatible with the pflag.StringSlice [1] parser that 'tkn bundle push' uses to parse CLI arguments.

https://pkg.go.dev/github.com/spf13/pflag#FlagSet.StringSlice

# Before you complete this pull request ...

Look for any open pull requests in the repository with the title "e2e-tests update" and 
see if there are recent e2e-tests updates that will be applicable to your change.

### CODE REVIEW

**Review by arewm — APPROVED** [review]

**Comment by chmeliik** [comment]
```
$ skopeo inspect --raw docker://quay.io/konflux-ci/pull-request-builds@sha256:48f87850d2c9c41cdde7c67571b3054dc0f14de01337f1f940f1231502625289 | jq '.annotations["org.opencontainers.image.description"]' -r

Clones redhat-appstudio/infra-deployments repository, runs script in "SCRIPT" parameter, generates pull-request for redhat-appstudio/infra-deployments repository.
```

The description of the update-infra-deployments task, which I updated in a test commit to contain both double-quotes and a comma, was preserved correctly
:tada:

**Pull request merged**
