### PR TITLE
Revert "[ISV-5221] Add new step to inject and push SBOMs in build-ima…

### PR DESCRIPTION
**Pull request by rcerven**
…ge-index task."

This reverts commit 05cb6766a2d851b4473d1a4a7913eb8d3ff5e969.

# Before you complete this pull request ...

Look for any open pull requests in the repository with the title "e2e-tests update" and 
see if there are recent e2e-tests updates that will be applicable to your change.

reverting it because it is causing problems with results limit, since it added more steps

### CODE REVIEW

**Review by arewm — APPROVED** [review]
These changes are causing the Tekton results to overflow since new steps results in a smaller space for results in each task step.

**Review by chmeliik — CHANGES_REQUESTED** [review]
I would like stronger proof that the problem was the result limit. Have you tested with the affected user that this resolves the issue?

**Comment by chmeliik** [comment]
> I would like stronger proof that the problem was the result limit. Have you tested with the affected user that this resolves the issue?

Probably no need to bother. The affected user was using an older version of the task, this change wasn't even included. We can probably close this.

**Pull request closed without merging**
