### PR TITLE
Clamav: parse version from clamscan

### PR DESCRIPTION
**Pull request by MartinBasti**
# Before you complete this pull request ...

Look for any open pull requests in the repository with the title "e2e-tests update" and 
see if there are recent e2e-tests updates that will be applicable to your change.

### CODE REVIEW

**Review by jsztuka — APPROVED** [review]
thanks for this, lgtm

**Review by chipspeak — APPROVED** [review]
LGTM and thanks for this and the glorious sed

**Comment by kasemAlem** [comment]
require rebase ?

**Comment by MartinBasti** [comment]
Rebased, I don;t think that it's the root cause, root cause is dying cluster

**Pull request merged**
