### PR TITLE
SDCICD-1337: run generate bundle as root

### PR DESCRIPTION
**Pull request by jbpratt**
needed to write out the generated files

Signed-off-by: Brady Pratt <bpratt@redhat.com>

### CODE REVIEW

**Review by chmeliik — COMMENTED** [review]
> needed to write out the generated files

Is it? It shouldn't be :thinking: 

AFAIK the buildah task only needs SETFCAP because it runs `unshare -r` (mapping user 0 in a new user namespace) https://man7.org/linux/man-pages/man7/capabilities.7.html

**Comment by jbpratt** [comment]
> > needed to write out the generated files
> 
> Is it? It shouldn't be 🤔
> 
> AFAIK the buildah task only needs SETFCAP because it runs `unshare -r` (mapping user 0 in a new user namespace) https://man7.org/linux/man-pages/man7/capabilities.7.html

Sorry @chmeliik , this may be my misunderstanding. I'm getting permission denied when trying to actually use the tasks built from konflux (this wasn't happening previously). It looks like most of the tasks set this capability

```
[generate-olm-bundle : operator-sdk-generate-bundle] Building a ClusterServiceVersion without an existing base
[generate-olm-bundle : operator-sdk-generate-bundle] time="2024-07-29T05:47:04Z" level=warning msg="ClusterServiceVersion validation: [OperationFailed] provided API should have an example annotation"
[generate-olm-bundle : operator-sdk-generate-bundle] time="2024-07-29T05:47:04Z" level=fatal msg="Error generating bundle manifests: error generating ClusterServiceVersion: open bundle/manifests/osd-example-operator.clusterserviceversion.yaml: permission denied"
```

```
$ grep SETFCAP -r
.tekton/tasks/buildah.yaml:          - SETFCAP
.tekton/tasks/buildah.yaml:          - SETFCAP
.tekton/tasks/e2e-test.yaml:          - SETFCAP
task/build-image-manifest/0.1/build-image-manifest.yaml:          - SETFCAP
task/buildah-oci-ta/0.1/buildah-oci-ta.yaml:            - SETFCAP
task/buildah-oci-ta/0.1/buildah-oci-ta.yaml:            - SETFCAP
task/buildah-oci-ta/0.2/buildah-oci-ta.yaml:            - SETFCAP
task/buildah-oci-ta/0.2/buildah-oci-ta.yaml:            - SETFCAP
task/buildah-remote-oci-ta/0.1/buildah-remote-oci-ta.yaml:        - SETFCAP
task/buildah-remote-oci-ta/0.1/buildah-remote-oci-ta.yaml:        - SETFCAP
task/buildah-remote-oci-ta/0.2/buildah-remote-oci-ta.yaml:        - SETFCAP
task/buildah-remote-oci-ta/0.2/buildah-remote-oci-ta.yaml:        - SETFCAP
task/buildah-remote/0.1/buildah-remote.yaml:        - SETFCAP
task/buildah-remote/0.1/buildah-remote.yaml:        - SETFCAP
task/buildah-remote/0.2/buildah-remote.yaml:        - SETFCAP
task/buildah-remote/0.2/buildah-remote.yaml:        - SETFCAP
task/buildah-rhtap/0.1/buildah-rhtap.yaml:          - SETFCAP
task/buildah/0.1/buildah.yaml:          - SETFCAP
task/buildah/0.1/buildah.yaml:          - SETFCAP
task/buildah/0.2/buildah.yaml:          - SETFCAP
task/buildah/0.2/buildah.yaml:          - SETFCAP
task/clair-scan/0.1/clair-scan.yaml:            - SETFCAP
task/clair-scan/0.1/clair-scan.yaml:            - SETFCAP
task/fbc-validation/0.1/fbc-validation.yaml:            - SETFCAP
task/inspect-image/0.1/inspect-image.yaml:          - SETFCAP
task/oci-copy-oci-ta/0.1/oci-copy-oci-ta.yaml:            - SETFCAP
task/oci-copy/0.1/oci-copy.yaml:            - SETFCAP
task/rpm-ostree/0.1/rpm-ostree.yaml:        - SETFCAP
task/rpm-ostree/0.1/rpm-ostree.yaml:        - SETFCAP
task/s2i-java/0.1/s2i-java.yaml:          - SETFCAP
task/s2i-java/0.1/s2i-java.yaml:          - SETFCAP
task/s2i-nodejs/0.1/s2i-nodejs.yaml:          - SETFCAP
task/s2i-nodejs/0.1/s2i-nodejs.yaml:          - SETFCAP
task/sbom-json-check/0.1/sbom-json-check.yaml:          - SETFCAP
task/source-build-oci-ta/0.1/source-build-oci-ta.yaml:            - SETFCAP
task/source-build/0.1/source-build.yaml:            - SETFCAP
task/opm-render-bundles/0.1/opm-render-bundles.yaml:            - SETFCAP
```

**Comment by chmeliik** [comment]
> Sorry @chmeliik , this may be my misunderstanding. I'm getting permission denied when trying to actually run the task built from konflux (this wasn't happening previously). It looks like most of the tasks set this capability
> 
> ```
> [generate-olm-bundle : operator-sdk-generate-bundle] Building a ClusterServiceVersion without an existing base
> [generate-olm-bundle : operator-sdk-generate-bundle] time="2024-07-29T05:47:04Z" level=warning msg="ClusterServiceVersion validation: [OperationFailed] provided API should have an example annotation"
> [generate-olm-bundle : operator-sdk-generate-bundle] time="2024-07-29T05:47:04Z" level=fatal msg="Error generating bundle manifests: error generating ClusterServiceVersion: open bundle/manifests/osd-example-operator.clusterserviceversion.yaml: permission denied"
> ```

Does adding SETFCAP fix the issue? Maybe the task needs to run as root instead. IIRC the clone task runs as root, thus kind of forcing all the other tasks that want to write into the source dir to run as root too https://github.com/konflux-ci/build-definitions/blob/8a2d1f0f2760d95e646b3ccbfb299e2f9666748b/task/git-clone/0.1/git-clone.yaml#L148-L151

**Comment by jbpratt** [comment]
> Does adding SETFCAP fix the issue? Maybe the task needs to run as root instead

Sorry about that, you are right. I tested with both there then convinced myself running as root was incorrect :smile: updating everything now! Thanks for your help!!

**Review by chmeliik — APPROVED** [review]

**Pull request merged**
