### PR TITLE
redirect task to the new quay repo konflux-ci

### PR DESCRIPTION
**Pull request by kasemAlem**
# Before you complete this pull request ...

Look for any open pull requests in the repository with the title "e2e-tests update" and 
see if there are recent e2e-tests updates that will be applicable to your change.

### CODE REVIEW

**Review by dirgim — APPROVED** [review]
LGTM

**Review by Josh-Everett — APPROVED** [review]

**Review by tnevrlka — CHANGES_REQUESTED** [review]
@kasemAlem Could you please rebase the commits so they're meaningful? 
Squash merge isn't used in this repository AFAIK so all four of them would get to the main branch. 

Single commit named `redirect task to the new quay repo konflux-ci` is fine by me

**Review by tnevrlka — APPROVED** [review]

**Comment by kasemAlem** [comment]
> @kasemAlem Could you please rebase the commits so they're meaningful? Squash merge isn't used in this repository AFAIK so all four of them would get to the main branch.
> 
> Single commit named `redirect task to the new quay repo konflux-ci` is fine by me

Thanks @tnevrlka for the important comment, I've squasahed it .

**Pull request merged**
