### PR TITLE
Add ssh keepalives into buildah-remote to prevent (or at least debug) the ssh conection interruptions

### PR DESCRIPTION
**Pull request by mshaposhnik**
It is reported some ssh conection interruptions during the long running remote build tasks. It is not yet 100% clear what causes it, but sending those keepalives might help to keep the channel up, or understood which side is closing the connections.
See https://issues.redhat.com/browse/KFLUXBUGS-1523 for more details

### CODE REVIEW

**Comment by mshaposhnik** [comment]
@chmeliik  @brianwcook pls TAL

**Review by ifireball — CHANGES_REQUESTED** [review]
you need to update the `task-generator/remote` tool to generate the remote tasks with this change. While we may get rid of it soon, we still use it, so without updating it your changes will be lost when the next person comes along and runs it.

**Comment by mshaposhnik** [comment]
@ifireball yes i figured that out and did so, please make sure you're on the latest version :)

**Review by ifireball — APPROVED** [review]
ok,
/lgtm

**Review by chmeliik — APPROVED** [review]

**Pull request merged**
