### PR TITLE
feat(STONEINTG-947): migrate the clamav db to konflux-ci repo

### PR DESCRIPTION
**Pull request by kasemAlem**
Integration team migrating the quay  repo of Clamav DB to  Konflux-ci orq , 
in this PR we redirect the task and renovate to the new repo 

for more details review  [STONEINTG-947](https://issues.redhat.com/browse/STONEINTG-947)

### CODE REVIEW

**Comment by kasemAlem** [comment]
we see the pushes made to the new repo same as the old one : 

Screenshot from 2024-11-06 12-34-39

**Review by dirgim — APPROVED** [review]
LGTM

**Review by hongweiliu17 — APPROVED** [review]
LGTM

**Review by jsztuka — APPROVED** [review]
lgtm

**Pull request closed without merging**
