### PR TITLE
Configurable public key path for EC pipelines

### PR DESCRIPTION
**Pull request by gbenhaim**
Allow to mention the path to the public key in the enterprise-contract pipelines. This is needed when running on non OCP k8s cluster.

### CODE REVIEW

**Comment by lcarva** [comment]
Looks reasonable to me besides what Zoran commented.

**Comment by gbenhaim** [comment]
@lcarva @zregvart done

**Review by lcarva — APPROVED** [review]
/lgtm

**Review by zregvart — APPROVED** [review]

**Pull request merged**
