### PR TITLE
De-duplicate attachment of OCI artifacts

### PR DESCRIPTION
**Pull request by ralphbean**
In PSSECAUT-605, a user reports that there is some funny behavior that is likely due to us invoking oras attach *twice* here.

There's no good reason to do it twice. Let's instead invoke it once, without specifying the distribution spec, and let oras choose for us.

### CODE REVIEW

**Review by dirgim — APPROVED** [review]
LGTM

**Review by hongweiliu17 — APPROVED** [review]
LGTM

**Comment by kasemAlem** [comment]
I've rebased and now all checks are passing @ralphbean

**Comment by ralphbean** [comment]
Thanks @kasemAlem !

**Pull request merged**
