### PR TITLE
buildah: resolve BUILD_ARGS in base images

### PR DESCRIPTION
**Pull request by chmeliik**
It is possible to use a build arg to specify the base image for a stage:

    ARG BASE_IMAGE=foo

    FROM $BASE_IMAGE

    ...

Pass --build-arg values to dockerfile-json to make sure we resolve the
base images properly.

### CODE REVIEW

**Comment by chmeliik** [comment]
Tested in https://github.com/konflux-ci/build-service/pull/346

**Review by mmorhun — APPROVED** [review]

**Comment by chmeliik** [comment]
Clarified BUILD_ARGS vs. BUILD_ARGS_FILE precedence in a comment, otherwise no change

**Review by tnevrlka — APPROVED** [review]

**Pull request merged**
