### PR TITLE
feat: add a script to generate an asciidocs index

### PR DESCRIPTION
**Pull request by ralphbean**
This is here as an experiment at the moment to see what it would look like if we generated a table of available tasks for the docs at https://github.com/konflux-ci/konflux-ci for KONFLUX-1229.

### CODE REVIEW

**Comment by ralphbean** [comment]
Example output at https://pr-129--konflux-docs.netlify.app/tasks/ rendered from https://github.com/konflux-ci/docs/pull/129

**Comment by arewm** [comment]
Thanks for this!

* I am not sure if a table will be the best format. Maybe a structure like what we have for our glossary would be better? https://konflux-ci.dev/docs/glossary/
* Any kustomized tasks do not show a description. Should we make those work better?
* Should we not render any tasks that have the expiration configured like https://github.com/konflux-ci/build-definitions/blob/main/task/sbom-json-check/0.2/sbom-json-check.yaml#L7 ?
* Should we specify an input list (or an exclusion list) so that all tasks are not included or should we instead focus on getting the extra tasks out of the repository?
* We should probably start creating descriptions for our pipelines as well so that we don't have to manually curate a list like this: https://pr-126--konflux-docs.netlify.app/advanced-how-tos/installing/enabling-builds/#available-pipelines

**Comment by zregvart** [comment]
Do we need more bash in this repository? We tackled a very similar issue in EC by using [golang + template](https://github.com/enterprise-contract/ec-cli/tree/main/internal/documentation/asciidoc/tekton).

**Comment by ralphbean** [comment]
A comment from https://issues.redhat.com/browse/KONFLUX-1229:

> And, for the centralized documentation bit, perhaps we should lean on artifacthub for this.
> 
> See https://artifacthub.io/packages/search?repo=tekton-catalog-tasks&sort=relevance&page=1 for an example.
> 
> If we got all of build-definitions and release-service-catalog published there, we could link to pages like https://artifacthub.io/packages/search?repo=konflux-build-definitions&sort=relevance and https://artifacthub.io/packages/search?repo=konflux-release-catalog&sort=relevance as indices.

Maybe we shouldn't build our own list at all?

**Comment by ralphbean** [comment]
I'm going to drop this and move the script over to https://github.com/konflux-ci/docs/pull/129

**Comment by ralphbean** [comment]
Related: https://github.com/konflux-ci/build-definitions/pull/756

**Pull request closed without merging**
