### PR TITLE
improve completeness of FBC validation migration

### PR DESCRIPTION
**Pull request by arewm**
# Before you complete this pull request ...

Look for any open pull requests in the repository with the title "e2e-tests update" and 
see if there are recent e2e-tests updates that will be applicable to your change.

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
/lgtm

**Review by dirgim — DISMISSED** [review]
LGTM

**Review by dirgim — APPROVED** [review]
LGTM

**Comment by arewm** [comment]
This is a non-code change but improves the migration. Force merging.

**Pull request merged**
