### PR TITLE
Delete source to image pipelines and tasks

### PR DESCRIPTION
**Pull request by mmorhun**
Since S2I pipelines (and corresponding tasks) is not used anymore for quite some time, we are removing them.

### CODE REVIEW

**Review by chmeliik — COMMENTED** [review]
Should we wait until the s2i tasks are deprecated according to the expires-on label?

**Comment by mmorhun** [comment]
@chmeliik the tasks are not used anywhere, I think it's safe to delete now.

**Review by tkdchen — COMMENTED** [review]
These lines are also deprecated:

https://github.com/konflux-ci/build-definitions/blob/main/hack/build-and-push.sh#L278-L279

**Review by chmeliik — APPROVED** [review]
:tada:

**Review by tkdchen — APPROVED** [review]

**Pull request merged**
