### PR TITLE
Use `hermetic` param in FBC builder pipeline to configure `build-container` task

### PR DESCRIPTION
**Pull request by pierDipi**
Fixes https://github.com/konflux-ci/build-definitions/issues/1426

Remove hardcoded `HERMETIC="true"` in `build-container` task for the FBC pipeline.

# Before you complete this pull request ...

Look for any open pull requests in the repository with the title "e2e-tests update" and 
see if there are recent e2e-tests updates that will be applicable to your change.

### CODE REVIEW

**Comment by MartinBasti** [comment]
Readme has to be regenerated.

I see an issue here, that FBC is by design hermetic, so there isn't much to change.
By using param `hermetic` from pipeline, which is false by default, existing users may start see errors from enterprise check. It's incompatible change for me. 

Unused param is not nice but, breaking existing workflows must be taken with care.

From git history I see that the enforcement for FBC to be always hermetic was intentional.

@mmorhun WDYT?

**Comment by MartinBasti** [comment]
@pierDipi do you have any use case, why FBC build shouldn't be hermetic?

**Comment by MartinBasti** [comment]
ah, actually it won't break existing builds, in will affect only new components

However, I'd like to hear opinions from the other maintainers

**Comment by chmeliik** [comment]
Yeah `hermetic` shouldn't default to `false` for the fbc pipeline (though that's fixable by kustomize)

**Comment by pierDipi** [comment]
Our use case is too build the index image similarly to how we're currently doing here https://github.com/openshift-knative/serverless-operator/blob/main/olm-catalog/serverless-operator/index/Dockerfile. 

There we `opm render` bundle images of previous versions so that we can test upgrades and downgrades (`v1 -> v2 -> <current version>`)

```
RUN /bin/opm render --skip-tls-verify -o yaml \
registry.ci.openshift.org/knative/release-1.33.0:serverless-bundle \
registry.ci.openshift.org/knative/release-1.34.0:serverless-bundle \
      registry.ci.openshift.org/knative/release-1.35.0:serverless-bundle >> /configs/index.yaml || \
    /bin/opm render --skip-tls-verify -o yaml \
registry.ci.openshift.org/knative/release-1.33.0:serverless-bundle \
registry.ci.openshift.org/knative/release-1.34.0:serverless-bundle \
      registry.ci.openshift.org/knative/serverless-bundle:main >> /configs/index.yaml
```

while we can workaround and refactor the FBC build, it's not a trivial change for us and I believe having the parameter and using it, it's very handy while we transition to Konflux

---

I'm happy to change the default Pipeline `param` value for FBC pipelines to be `true` by default

**Comment by chmeliik** [comment]
> I'm happy to change the default parameter value for FBC pipelines to be `hermetic=true` by default, even though, in my opinion, having a consistent value across all default pipelines (either all `false` or `true`) seems more intuitive as a user

General docker builds typically don't work hermetically out of the box, the user either needs to make some more changes to their build process or needs to configure an exception from the EC policy that requires hermetic builds.

FBC builds typically do work hermetically out of the box, your build is the first we've seen where that's not the case.

I don't really see an issue with having different defaults for different pipelines

**Comment by pierDipi** [comment]
Pushed the updated default value, running: `$ kustomize build pipelines/fbc-builder/ --load-restrictor LoadRestrictionsNone`

I get the expected `hermetic=true` by default:

```yaml
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  labels:
    pipelines.openshift.io/runtime: fbc
    pipelines.openshift.io/strategy: fbc
    pipelines.openshift.io/used-by: build-cloud
  name: fbc-builder
spec:
  description: |
    This pipeline is ideal for building and verifying [file-based catalogs](https://konflux-ci.dev/docs/advanced-how-tos/building-olm.adoc#building-the-file-based-catalog).

    _Uses `buildah` to create a container image. Its build-time tests are limited to verifying the included catalog and do not scan the image.
    This pipeline is pushed as a Tekton bundle to [quay.io](https://quay.io/repository/konflux-ci/tekton-catalog/pipeline-fbc-builder?tab=tags)_
  finally:
  - name: show-sbom
    params:
    - name: IMAGE_URL
      value: $(tasks.build-image-index.results.IMAGE_URL)
    taskRef:
      name: show-sbom
      version: "0.1"
  - name: show-summary
    params:
    - name: pipelinerun-name
      value: $(context.pipelineRun.name)
    - name: git-url
      value: $(tasks.clone-repository.results.url)?rev=$(tasks.clone-repository.results.commit)
    - name: image-url
      value: $(params.output-image)
    - name: build-task-status
      value: $(tasks.build-image-index.status)
    taskRef:
      name: summary
      version: "0.2"
    workspaces:
    - name: workspace
      workspace: workspace
  params:
  - description: Source Repository URL
    name: git-url
    type: string
  - default: ""
    description: Revision of the Source Repository
    name: revision
    type: string
  - description: Fully Qualified Output Image
    name: output-image
    type: string
  - default: .
    description: Path to the source code of an application's component from where
      to build image.
    name: path-context
    type: string
  - default: Dockerfile
    description: Path to the Dockerfile inside the context specified by parameter
      path-context
    name: dockerfile
    type: string
  - default: "false"
    description: Force rebuild image
    name: rebuild
    type: string
  - default: "false"
    description: Skip checks against built image
    name: skip-checks
    type: string
  - default: "true"
    description: Execute the build with network isolation
    name: hermetic
    type: string
  - default: ""
    description: Build dependencies to be prefetched by Cachi2
    name: prefetch-input
    type: string
  - default: ""
    description: Image tag expiration time, time values could be something like 1h,
      2d, 3w for hours, days, and weeks, respectively.
    name: image-expires-after
  - default: "false"
    description: Build a source image.
    name: build-source-image
    type: string
  - default: "false"
    description: Add built image into an OCI image index
    name: build-image-index
    type: string
  results:
  - name: IMAGE_URL
    value: $(tasks.build-image-index.results.IMAGE_URL)
  - name: IMAGE_DIGEST
    value: $(tasks.build-image-index.results.IMAGE_DIGEST)
  - name: CHAINS-GIT_URL
    value: $(tasks.clone-repository.results.url)
  - name: CHAINS-GIT_COMMIT
    value: $(tasks.clone-repository.results.commit)
  tasks:
  - name: init
    params:
    - name: image-url
      value: $(params.output-image)
    - name: rebuild
      value: $(params.rebuild)
    - name: skip-checks
      value: $(params.skip-checks)
    taskRef:
      name: init
      version: "0.2"
  - name: clone-repository
    params:
    - name: url
      value: $(params.git-url)
    - name: revision
      value: $(params.revision)
    runAfter:
    - init
    taskRef:
      name: git-clone
      version: "0.1"
    when:
    - input: $(tasks.init.results.build)
      operator: in
      values:
      - "true"
    workspaces:
    - name: output
      workspace: workspace
    - name: basic-auth
      workspace: git-auth
  - name: build-container
    params:
    - name: IMAGE
      value: $(params.output-image)
    - name: DOCKERFILE
      value: $(params.dockerfile)
    - name: CONTEXT
      value: $(params.path-context)
    - name: HERMETIC
      value: $(params.hermetic)
    - name: IMAGE_EXPIRES_AFTER
      value: $(params.image-expires-after)
    - name: COMMIT_SHA
      value: $(tasks.clone-repository.results.commit)
    runAfter:
    - clone-repository
    taskRef:
      name: buildah
      version: "0.2"
    when:
    - input: $(tasks.init.results.build)
      operator: in
      values:
      - "true"
    workspaces:
    - name: source
      workspace: workspace
# ...
```

**Comment by pierDipi** [comment]
> Readme has to be regenerated.

Sorry, how do I do this?

**Comment by MartinBasti** [comment]
> > Readme has to be regenerated.
> 
> Sorry, how do I do this?
Failed check is suggesting how to
image

**Comment by pierDipi** [comment]
Done

**Comment by pierDipi** [comment]
@MartinBasti @chmeliik is there anything else missing for this PR ?

**Review by chmeliik — APPROVED** [review]
Just forgot about this PR, sorry!

**Pull request merged**
