### PR TITLE
sast: Fix sast unicode check

### PR DESCRIPTION
**Pull request by hanchuntao**
Fix find_unicode_control parameters issue in sast-unicode-check
    
In the previous code, the parameters will be displayed as one parameter,
should split them as many parameters

Resolves: https://issues.redhat.com/browse/OSH-764

### CODE REVIEW

**Comment by hanchuntao** [comment]
Hello, please review this PR, thanks!

**Comment by hanchuntao** [comment]
@Josh-Everett @sonam1412

**Comment by kdudka** [comment]
@hanchuntao This fix had already been included in #1524: https://github.com/konflux-ci/build-definitions/pull/1524/commits/092a62087708adbed9dc3302a5baa26128f5e78d

**Comment by hanchuntao** [comment]
> @hanchuntao This fix had already been included in #1524: [092a620](https://github.com/konflux-ci/build-definitions/commit/092a62087708adbed9dc3302a5baa26128f5e78d)

@kdudka thanks you for your fix, so I will close this PR

**Pull request closed without merging**
